FROM node:14-alpine

WORKDIR /app

#COPY package.json package.json
#COPY package-lock.json package-lock.json

COPY . .

RUN npm install
RUN npm install -g nodemon

EXPOSE 3000
EXPOSE 9229

CMD ["nodemon", "--inspect=0.0.0.0", "./server/index.js", "--watch", "server"]
