FROM node:14-alpine

ENV USE_STATIC_MIDDLEWARE=true

WORKDIR /app

COPY package.json package.json
COPY package-lock.json package-lock.json

COPY . .

RUN npm install
RUN npm install -g nodemon

EXPOSE 3000
EXPOSE 9229

CMD ["nodemon", "--inspect", "./server/index.js", "--watch", "server"]
